### ISSUE TITLE
Unable to install bundle and ruby packages

### ISSUE THREAD

**Issue by Aju100** [coronainfonepal/coronainfonepal.github.io#23]
I followed the instructions as mentioned in README.md docs and it shows the error like this.

- System: Ubuntu 18.x version
- Ruby :2.5.1p57

![issue](https://user-images.githubusercontent.com/29862610/80047968-884da080-852e-11ea-8cf4-ef9c1cc09c18.png)

**Comment by coolbrg** [comment]
@Aju100  Either update bundler to the version `2.1.4` or remove `Gemfile.lock` and do `bundle install`.
